version: "3.3"

# ipv6 is not required for SSL Labs test, but for internet.nl test
# you must update your /etc/docker/daemon.json to enable this
# see https://docs.docker.com/config/daemon/ipv6/
networks:
  ipv6:
    enable_ipv6: true
    subnet: 2001:0DB8::/112

services:
  nginx:
    container_name: nginx
    image: nginxinc/nginx-unprivileged:stable-alpine-slim
    restart: unless-stopped
    networks:
      - ipv6
    ports:
      - 80:8080
      - 443:443
    environment:
      - TZ=Europe/Berlin
    volumes:
      # make sure the nginx user can can access these, this docker image uses GID:UID 101:101
      # for example: sudo chown -R 101:101 config/
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html:ro
      - ./logs:/var/log/nginx
      - ./ssl/domain.crt:/etc/ssl/domain.crt:ro
      - ./ssl/domain.key:/etc/ssl/domain.key:ro
      - ./ssl/ffdhe4096.pem:/etc/ssl/ffdhe4096.pem:ro
